<a href="https://colab.research.google.com/github/doa-2026/machine-learning/blob/main/column_Transfomer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
path="/content/drive/MyDrive/نسخة من cereal-kaggle-crawford-modified - sheet 1.csv"
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import set_config
set_config(transform_output="pandas")
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder
from sklearn.compose import ColumnTransformer
df=pd.read_csv(path)
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,NaN,4,1.0,130,10.0,5.0,6.0,280,25,top,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120.0,3,5.0,15,2.0,8.0,8.0,135,0,top,1.0,1.00,33.983679
2,All-Bran,K,C,70.0,4,1.0,260,9.0,7.0,5.0,320,25,top,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50.0,4,0.0,140,14.0,8.0,0.0,330,25,top,1.0,0.50,93.704912
4,Almond Delight,R,C,NaN,2,2.0,200,1.0,14.0,8.0,-1,25,NaN,1.0,0.75,34.384843

In [ ]:
X =df.drop(columns=["rating"])
y=df["rating"]
X_train ,X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [ ]:
num_col=X_train.select_dtypes(include="number").columns
mean_imputer=SimpleImputer(strategy="mean")
scaler=StandardScaler()
num_pipe=make_pipeline(mean_imputer,scaler)
tuple_num=("number",num_pipe,num_col)
tuple_num

('number',
 Pipeline(steps=[('simpleimputer', SimpleImputer()),
                 ('standardscaler', StandardScaler())]),
 Index(['calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars',
        'potass', 'vitamins', 'weight', 'cups'],
       dtype='object'))

In [ ]:
ord_col=["shelf"]
ord_imputer=SimpleImputer(strategy="most_frequent")
order=["bottom","middle","top"]
ord_encoder=OrdinalEncoder(categories=[order])
scaler=StandardScaler()
ord_pipe=make_pipeline(ord_imputer,ord_encoder,scaler)
tuple_ord=("ordinal",ord_pipe,ord_col)
tuple_ord

('ordinal',
 Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('ordinalencoder',
                  OrdinalEncoder(categories=[['bottom', 'middle', 'top']])),
                 ('standardscaler', StandardScaler())]),
 ['shelf'])

In [ ]:
cat_col=X_train.select_dtypes("object").drop(columns=ord_col).columns
cat_imputer=SimpleImputer(strategy="constant",fill_value="Missing")
cat_encoder=OneHotEncoder(sparse_output=False,handle_unknown="ignore")
cat_pipe=make_pipeline(cat_imputer,cat_encoder)
tuple_cat=("categorical",cat_pipe,cat_col)
tuple_cat

('categorical',
 Pipeline(steps=[('simpleimputer',
                  SimpleImputer(fill_value='Missing', strategy='constant')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 Index(['name', 'mfr', 'type'], dtype='object'))

In [ ]:
col_tran=ColumnTransformer([tuple_num,tuple_ord,tuple_cat],verbose_feature_names_out=False)
col_tran.fit(X_train)

ColumnTransformer(transformers=[('number',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer()),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 Index(['calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars',
       'potass', 'vitamins', 'weight', 'cups'],
      dtype='object')),
                                ('ordinal',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ordinalenco...
                                                  OrdinalEncoder(categories=[['bottom',
                                                                              'middle',
                                                                              'top']])),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['shelf']),
                                ('categorical',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(fill_value='Missing',
                                                                strategy='constant')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['name', 'mfr', 'type'], dtype='object'))],
                  verbose_feature_names_out=False)

In [ ]:
X_train_proccessing=col_tran.transform(X_train)
X_test_proccessing=col_tran.transform(X_test)
X_test_proccessing.head()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,weight,...,mfr_A,mfr_G,mfr_K,mfr_Missing,mfr_N,mfr_P,mfr_Q,mfr_R,type_C,type_H
4,0.0,-0.524507,1.088047,0.534600,-0.444692,-0.217084,0.366247,-1.335583,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
35,0.0,-1.403826,1.088047,0.763285,-0.444692,-0.662988,1.063009,-0.680533,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10,0.0,-1.403826,1.088047,0.763285,-0.871334,-0.662988,1.295263,-0.822935,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
0,0.0,1.234133,0.040298,-0.265796,3.395084,-2.223649,-0.098261,2.665919,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
45,0.0,1.234133,2.135796,-0.037111,0.408592,0.228819,1.063009,1.099495,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [ ]:
X_test_proccessing.head()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,weight,...,mfr_A,mfr_G,mfr_K,mfr_Missing,mfr_N,mfr_P,mfr_Q,mfr_R,type_C,type_H
4,0.0,-0.524507,1.088047,0.534600,-0.444692,-0.217084,0.366247,-1.335583,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
35,0.0,-1.403826,1.088047,0.763285,-0.444692,-0.662988,1.063009,-0.680533,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10,0.0,-1.403826,1.088047,0.763285,-0.871334,-0.662988,1.295263,-0.822935,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
0,0.0,1.234133,0.040298,-0.265796,3.395084,-2.223649,-0.098261,2.665919,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
45,0.0,1.234133,2.135796,-0.037111,0.408592,0.228819,1.063009,1.099495,-0.128403,-0.173782,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0